name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT_PRODUCTION}}
  RUN_REGION: us-central1
  PROJECT_NAME: product-builder

jobs:
  
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Export gcloud related env variable
        run: export CLOUDSDK_PYTHON="/usr/bin/python3"

      - name: Google Auth
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.RUN_SA_KEY_PRODUCTION }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'


      # Build and push image to Google Container Registry
      - name: Build
        run: |-
          gcloud builds submit \
            --timeout "1h" \
            --tag "gcr.io/$PROJECT_ID/$PROJECT_NAME-${GITHUB_REF##*/}:$GITHUB_SHA" 

      # Deploy image to Cloud Run for API
      - name: Deploy API
        run: |-
          gcloud run deploy "$PROJECT_NAME-${GITHUB_REF##*/}" \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$PROJECT_NAME-${GITHUB_REF##*/}:$GITHUB_SHA" \
            --platform "managed" \
            --cpu 0.25 \
            --memory "500Mi" \
            --timeout 1m \
            --allow-unauthenticated \
            --set-env-vars "ENVIRONMENT=PRODUCTION" \
            --set-env-vars "OPENAI_API_KEY=$OPENAI_API_KEY" \
            --set-env-vars "AWS_S3_ACCESS_KEY=$AWS_S3_ACCESS_KEY" \
            --set-env-vars "AWS_S3_ACCESS_SECRET=$AWS_S3_ACCESS_SECRET" \
