name: Push to dev

on:
  push:
    branches:
      - "dev"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Env
      run: pip install pipenv && pipenv install
    - name: Run Test
      env:
        PYTHONPATH: ./
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
        AWS_S3_ACCESS_SECRET: ${{ secrets.AWS_S3_ACCESS_SECRET }}
      run: pipenv run python -m unittest tests/basic.py